### ISSUE TITLE
Malformed query

### ISSUE THREAD

**Issue by ben-manes** [algolia/algoliasearch-client-java#15]
I tried upgrading from 1.x to 2.x, which is only minor API changes. I'm still using JSONObject through Jackson, rather than convert to pass in the Jackson object directly. That seems to work fine for adding, but querying generates an invalid string.

```
trutypoTolerance=falseallowTyposOnNumericTokens=falsehitsPerPage=8tagsFilters=(user:275,user:ben@loaddocs.co,firm:12)
```

When I remove all query settings (`query.setQuery(userQuery)` only) then results appear. Of course that can't be used (e.g. I'm using tags for permission filtering). The problem appears to be `Query#toParam()` is not joining the strings correctly and merely appending each entry together. Instead it should either use Guava's `Joiner` (as an existing dependency) or construct a `List<String>` and use `collect(joining("&"))`.

**Comment by ben-manes** [comment]
Oh, it looks like this has been fixed on master. Can you please release?

**Comment by ElPicador** [comment]
I've not tested the v2 with `JSONObject`. Would you mind adding some tests?

I've released the 2.1.0, that contains the fix: https://github.com/algolia/algoliasearch-client-java-2/commit/38f0ad77558302e9a1a49c02268216547277150f

**Comment by ben-manes** [comment]
Thanks! It works great now.

No tests should be required. I'm using [jackson.datatype.jsonorg](https://github.com/FasterXML/jackson-datatype-json-org) which allows Jackson to marshall JSONObjects. This made working with the v1 API simple and upgrading to be straightforward. I'd recommend documenting that approach in the migration guide, as others may think that they need a more invasive rewrite.

**Comment by ElPicador** [comment]
Thanks, I didn't know this library. I'll add it to the migration guide
