### ISSUE TITLE
java.lang.IllegalArgumentException: Class file is Java 8 but max supported is Java 7

### ISSUE THREAD

**Issue by Edijae** [algolia/algoliasearch-client-java#213]
I am trying to use algolia in my android backend module(which is deployed to app engine) and i have included algolia in my `build.gradle`

`compile 'com.algolia:algoliasearch-appengine:2.2.1'`
But when i try to deploy my module, i get this error

**java.lang.IllegalArgumentException: Class file is Java 8 but max supported is Java 7: com/algolia/search/AppEngineAPIClientBuilder.class in /home/c/Sp/py/build/exploded-app/WEB-INF/lib/algoliasearch-appengine-2.2.1.jar
Unable to update app: Class file is Java 8 but max supported is Java 7: com/algolia/search/AppEngineAPIClientBuilder.class in /home/c/Sp/py/build/exploded-app/WEB-INF/lib/algoliasearch-appengine-2.2.1.jar
Please see the logs [/tmp/appcfg636725079429378824.log] for further information.**

How can i solve the error?

**Comment by ElPicador** [comment]
Are you using the standard environment or the flexible one? (see: https://cloud.google.com/appengine/docs)

From what I see, you are using the standard one.

**Comment by Edijae** [comment]
yes, standard one

**Comment by Edijae** [comment]
Does that mean i can't use algolia in standard enviroment?

**Comment by ElPicador** [comment]
Basically yes. The issue is to support an asynchronous version we need Java 1.8.
Nevertheless, you can still use the version 1 of the API Client (https://github.com/algolia/algoliasearch-client-java). It's maintained but deprecated. The Java API is a bit different (less type safety) but it works with java 1.5+

**Comment by Edijae** [comment]
Yeah it worked. sorry for late reply, I was watching Donald trump being sworn in.
