### ISSUE TITLE
Cannot call ApacheAPIClientBuilder.build()

### ISSUE THREAD

**Issue by playtowork** [algolia/algoliasearch-client-java#226]
I am trying to use Algolia with Play framework. I am following the documentation as shown at either https://github.com/algolia/algoliasearch-client-java-2 or https://www.algolia.com/doc/guides/indexing/import-synchronize-data/java/.

In my build.sbt, I am specifying:
```Scala
libraryDependencies ++= Seq(
    ...
    "com.algolia"             % "algoliasearch"     % "2.7.0", // For Search-as-a-Service
)
```

In my Java code, I have the following:
```Java
    String myApplicationId = ...;
    String myApiKey = ...;
    ApacheAPIClientBuilder builder = new ApacheAPIClientBuilder(myApplicationId, myApiKey);
```
However, given this builder, I cannot call `build()` on it to create an `APIClient`. I do not have access to that function.

I have also tried pulling in `algoliasearch-common` as well as trying to use the async version by pulling in `algoliasearch-async`. Same problem in both cases. How am I supposed to make the `APIClient`?

**Comment by ElPicador** [comment]
That's weird, the `build()` method is public: https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/APIClientBuilder.java#L118-L131

What is the compilation error you have?

Furthermore, there is a Scala version of our APIClient. It's using scala `Future` so probably easier to integrate with play: https://github.com/algolia/algoliasearch-client-scala

**Comment by playtowork** [comment]
The compilation error I was seeing was:
```
cannot find symbol
  symbol:   class APIClient
  location: package com.algolia.search
```

I have been able to get it to compile by doing the following (including both `algoliasearch` and `algoliasearch-common`) in build.sbt:
```
libraryDependencies ++= Seq(
    ...
    "com.algolia"             % "algoliasearch"            % "2.7.0", // For Search-as-a-Service
    "com.algolia"             % "algoliasearch-common"     % "2.7.0", // For Search-as-a-Service
)
```

If this is the correct and suggested way to pull in the relevant Algolia dependencies for Play framework, then this should be documented.

**Comment by ElPicador** [comment]
It's weird because `algoliasearch-common` is a dependency of `algoliasearch` so it should be in your classpath. Could you give me the dependency tree generated by `sbt` when you do not add `algoliasearch-common`? You only need to add this plugin: https://github.com/jrudolph/sbt-dependency-graph

Furthermore, is there any reason for you not to use the Scala api client?

**Comment by ElPicador** [comment]
Can I close this one?

**Comment by ElPicador** [comment]
Closing it
