### ISSUE TITLE
Index a JSON object

### ISSUE THREAD

**Issue by ericholiveira** [algolia/algoliasearch-client-java#247]
Im trying to update the algolia library for version 2.x ...
On version 1.x i used to add a JSON object to the index, now i dont know how can i do this.
I have a legacy object indexed and for this reason the object on my backend is not equals to the object in algolia, and i dont want to keep two copies of the same object as it will be a hell to maintain both.

How can i index a simple Json object?

**Comment by ElPicador** [comment]
Have you tried using the [`jackson-datatype-json-org`](https://github.com/FasterXML/jackson-datatype-json-org). 

It enables you to use `JSONObject` with the API v2.x

**Comment by erich-oliveira-winnin** [comment]
Still cant use JSONObject...

I receive the following compilation error:
```
[error] ....scala:72: type mismatch;
[error]  found   : jsObj.type (with underlying type org.json.JSONObject)
[error]  required: ?0
[error]     index.saveObject(id,jsObj)
```
For the code:
```
val client = new AsyncHttpAPIClientBuilder(applicationId, apiKey).build()//new APIClient(applicationId, apiKey)
  val index = client.initIndex(indexNameMix)
val jsObj = new JSONObject(/*JSON string here*/)
    index.saveObject(id,jsObj)
```
Im using it in scala and im not using the scala library because i also dont know how to pass a simple json object to it instead of a case class

**Comment by ElPicador** [comment]
Have you registered the module? 
See https://github.com/FasterXML/jackson-datatype-json-org#registering-module and https://github.com/algolia/algoliasearch-client-java-2#json--jackson2

As for Scala, yes there is no simple way to transform a `JSONObject` to a `case class`. It's probably doable with shapeless or anything else.

**Comment by erich-oliveira-winnin** [comment]
Ive tried the following:
```
val mapper = new ObjectMapper()
mapper.registerModule(new JsonOrgModule())
val client = new AsyncHttpAPIClientBuilder(applicationId, apiKey).setObjectMapper(mapper).build()//new APIClient(applicationId, apiKey)
val index = client.initIndex(indexNameMix)
index.saveObject("SOME ID",new JSONObject())
```
And still have a compilation error:

```
found   : org.json.JSONObject
[error]  required: ?0
[error]     index.saveObject("SOME ID",new JSONObject())
```
Thx for your assistance.

**Comment by ElPicador** [comment]
Replace 
```
val index = client.initIndex(indexNameMix)
```

by

```
val index = client.initIndex(indexNameMix, classOf[JSONObject])
```

The method `initIndex(String index)` returns a `Index<?>` here you need to have it parametrised with a `JSONObject`

Does this work now?

**Comment by erich-oliveira-winnin** [comment]
Worked perfectly.
Thanks for your support
