### ISSUE TITLE
Browse : error when no elements retrieved

### ISSUE THREAD

**Issue by PaulinSanselme-Concord** [algolia/algoliasearch-client-java#32]
**What**
When calling the browse method with no elements in the Index, you will get an error.

**Why**
The first call of IndexIterator.hasNext() will always return true regardless if the query will actually be able to retrieve at least one element, hence breaking the iterator contract.
The doQuery method should be called in both hasNext() and next()  methods.

**How to reproduce**

```
final Index<ObjectID> index = client.initIndex(indexName, ObjectID.class);
try {
    final IndexIterable<ObjectID> items = index.browse(new Query());
    for (final ObjectID item : items) {
        System.out.println(item.getObjectID());
    }
} catch (final AlgoliaException e1) {
}
```

**Comment by ElPicador** [comment]
Thanks for this one as well
