### ISSUE TITLE
Browse : always retrieve all items in index

### ISSUE THREAD

**Issue by PaulinSanselme-Concord** [algolia/algoliasearch-client-java#33]
**What**
When calling the browse method, you will get all elements from the index regardless of the query you provide.
A consequence of this bug is that deleteByQuery clear the whole index.

**Why**
The query parameters are correctly set in APIClient.browse(...) in the AlgoliaRequest object but are not used when sending the request.

**How to reproduce**

```
final Index<ObjectID> index = client.initIndex(indexName, ObjectID.class);
try {
    final IndexIterable<ObjectID> items = index.browse(new Query().setFilters("This is ignored"));
    for (final ObjectID item : items) {
        System.out.println(item.getObjectID());
    }
} catch (final AlgoliaException e1) {
}
```

**Comment by ElPicador** [comment]
Thanks for the report, and thanks for the completeness of all the info to reproduce!
