### ISSUE TITLE
Algolia Dashboard still warns about outdated client

### ISSUE THREAD

**Issue by adamretter** [algolia/algoliasearch-client-java#337]
We were previously using version 2.9.0 of your client and so we updated to 2.10.0. However the Algolia Dashboard is still warning us that we are using an outdated client and simply says under *Operations* -> *API Client* tab: "Critical update (2.10.0)".

**Comment by adamretter** [comment]
We also occasionally see the following on the Dashboard: <img width="1223" alt="screen shot 2017-06-28 at 10 27 37" src="https://user-images.githubusercontent.com/1264057/27642333-80a6988c-5bec-11e7-80a2-5f305ec74a0a.png">

**Comment by ElPicador** [comment]
Do you mind continuing this issue on support. Could you sent an e-mail to support@algolia.com, with a link to this issue?

I'll handle it directly in support.

Thanks
