### ISSUE TITLE
passing an empty list to attributesToHighlight does not work

### ISSUE THREAD

**Issue by ehayman** [algolia/algoliasearch-client-java#345]
Hi, 
I have a customer reporting the following:

In the Java client, the `attributesToHighlight` is of type `List<String>` and is being added to a query builder here https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/objects/Query.java#L150 , which effectively invokes this method https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/objects/Query.java#L246 , where it is just ignored, if it is empty.

A workaround that I found so far is to pass to the `attributesToHighlight` a non-existent field, so that it’s not empty (like `attributesToHighlight=DUMMY`)

**Comment by ElPicador** [comment]
Indeed. I'll fix it right away
