### ISSUE TITLE
Eaten exception causing empty result

### ISSUE THREAD

**Issue by GregoryOrciuch** [algolia/algoliasearch-client-java#347]
Hi,

I just finished extensive debugging and found that if Jackson's Deserialization Exception  happens (in form of AlgoliaException) when Browsing indexes, the exception is eaten and empty result is returned.
It's here: https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/IndexIterator.java#L66

Line 66 in IndexIterator.java .
In my opinion the AlgoliaExeption should be thrown and at least LOG.error should be printed.

BR,
Gregory

**Comment by ElPicador** [comment]
Thanks for the report.

Indeed the exception is eaten. But apart from throwing a `RuntimeException`, I don't see what to do. 
I prefer not to have Logs in the API clients are it would need to expose a way to configure, tweak it.

So would a Runtime would be ok with you?

**Comment by GregoryOrciuch** [comment]
For me better to throw RuntimeException or AlgoliaException from there, so it does not hide the real problem of jackson's deserialization.

**Comment by ElPicador** [comment]
I can not throw a typed exception because the method the interface `Iterator` do not throw exceptions. So it must be a runtime

**Comment by GregoryOrciuch** [comment]
Good for me.
