### ISSUE TITLE
Could IndexSettings implement Serializable? 

### ISSUE THREAD

**Issue by chetaldrich** [algolia/algoliasearch-client-java#415]
Hello there, 

So I work with this library quite a bit in the context of [Apache Beam](https://beam.apache.org/), and specifically I use this library to output a bunch of elements that I transform inside Beam into POJOs that are converted into JSON and output to an Algolia index. 

The problem I find is that in order to use this here, I'm having to build a "copy" of the IndexSettings class with a method that builds an Algolia IndexSettings object as defined within this SDK because [Beam requires objects to be Serializable in certain contexts](https://beam.apache.org/documentation/programming-guide/#serializability). Is there a chance that the root [IndexSettings](https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/objects/IndexSettings.java) object could be made serializable?

**Comment by ElPicador** [comment]
I've made a PR to add `Serializable` to multiple objects. I'll try to release a new version today.
