### ISSUE TITLE
Index.addObject(Object) is not taking values from getters

### ISSUE THREAD

**Issue by SheikhG1900** [algolia/algoliasearch-client-java#418]
### Sample Class
```
class Student{
private String name = "my name";

public String getName(){ return name;}
public String setName(){ this.name = name }

public String getMessage(){
 return "test message";
}
```

### expecting result;
```
{
"name": "my name",
"message": "test message"
}

```
### actual result

```
{
"name": "my name"
}

```

**Comment by ElPicador** [comment]
Thanks for the report.
Did you specify a specific ObjectMapper? If yes what is the configuration?

**Comment by SheikhG1900** [comment]
No I didn't specify any configuration for ObjectMapper. Please share the configuration if it is required.

**Comment by ElPicador** [comment]
The proper configuration depends on your code and what you want to achieve, so I can't give it to you.
This `ObjectMapper` is the one used by the underlying json library: Jackons.
So you should look at the documentation of the ObjectMapper of Jackson: https://github.com/FasterXML/jackson-databind#10-minute-tutorial-configuration

**Comment by SheikhG1900** [comment]
Pretty satisfied. It is something related to configuration. I will see ObjectMapper documentation. Hopefully it will resolve my issue.  Thanks for your answer.
