### ISSUE TITLE
clojure compatibility reflection error

### ISSUE THREAD

**Issue by mrmcc3** [algolia/algoliasearch-client-java#451]
For releases after 2.10.0 basic interop from clojure causes a reflection error `Can't call public method of non-public class`

From discussion in https://github.com/algolia/algoliasearch-client-java-2/pull/335 below is an example to  reproduce

1. install the clojure command line tools https://clojure.org/guides/getting_started. `brew install clojure` on osx
2. declare the algolia dependency in a `deps.edn` file
``` clojure
{:deps {com.algolia/algoliasearch {:mvn/version "2.15.5"}}}
```
3. put sample repro in `algolia.clj`
``` clojure
;; configure the client and index
(def app-id "<app id here>")
(def api-key "<admin api key here>")
(def client (.build (com.algolia.search.ApacheAPIClientBuilder. app-id api-key)))
(def index (.initIndex client "repro"))

;; add an object with id 1 and wait for completion
(-> (.addObjects index [{"objectID" "1" "message" "it works!"}])
    (.waitForCompletion))

;; get the object back and print the message to console
(-> (.getObject index "1")
    (.get)
    (get "message")
    (println))

(System/exit 0)
```
4. run it with `clj algolia.clj` to produce the error
5. Repeat with version `2.10.0` in `deps.edn` and it prints `it works!` 

Hope this helps

**Comment by ElPicador** [comment]
Thanks for the issue, we'll have a look

**Comment by ElPicador** [comment]
I do reproduce the error with the clojure code.

As I said before the reflection trick to reproduce it doesn't work. But it's in fact more tricky.
I do not reproduce it when I launch the test in the source code of this project. But if I take the same test and put it on a another project I do reproduce the error.

I'll continue to investigate on how to reproduce in a test.

**Comment by ElPicador** [comment]
Ok so if I put the test ouside the `com.algolia` package I reproduce it \o/.

I'm working on the fix

**Comment by ElPicador** [comment]
I've made a fix that pass the tests. It should be available as a snapshot soon (waiting for travis build).
If possible could you try it?

**Comment by mrmcc3** [comment]
Yes I was able to build and the clojure sample above works.

**Comment by ElPicador** [comment]
Nice !
I'll release a new version ASAP

**Comment by ElPicador** [comment]
The `2.15.6` is released with the fix.
