### ISSUE TITLE
Index Copy with Scope Doesn't Work

### ISSUE THREAD

**Issue by SimonMorrow** [algolia/algoliasearch-client-java#459]
I’ve been trying to copy an index with scope (settings, synonyms and rules) using the Java API but I’ve getting an odd http back…

Snippet:
APIClient client = new ApacheAPIClientBuilder(FeedProcessor.algoliaApplicationId, FeedProcessor.algoliaApiKey).build();
Index index = client.initIndex(FeedProcessor.defaultIndexName, Product.class);

		try {
			index.copyTo(FeedProcessor.defaultIndexName + "_SM", Arrays.asList("settings", "synonyms", "rules"));
		} catch (AlgoliaException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
Error:
855 [main] DEBUG algoliasearch - Answer: {“message”:“Object must contains only destination or operation string attributes near line:1 column:54”,“status”:400}
875 [main] DEBUG algoliasearch - Got HTTP code 400
com.algolia.search.exceptions.AlgoliaHttpException: Object must contains only destination or operation string attributes near line:1 column:54

In looking at the http produced I could reproduce with the HTTP Rest API and it seems the Java API is passing the scope parameter as "scopes" when it is expecting it as "scope".

Thanks,

Simon

**Comment by ElPicador** [comment]
I've made a PR to fix this #460. I'll deploy a new version today.
