### ISSUE TITLE
getHits always return the same result

### ISSUE THREAD

**Issue by cecilcosta** [algolia/algoliasearch-client-java#472]
If I get the number of pages, create a loop, and set the page, every time I get the hits it returns the same result, therefore moving between pages doesn't have any result.

**Comment by ElPicador** [comment]
Thanks for the report.
I'm not sure to understand the exact bug. Could you provide a way to reproduce it?

**Comment by cecilcosta** [comment]
Do a query and get the results.
result.getHits() -> Gives you 20 hits due to we are on the first page.
result.setPage(2) -> We are switching to the 3rd pagel.
result.getHits() -> Still gives you the first 20 results.

**Comment by ElPicador** [comment]
Yes, that's expected.
The `result` you get from a search is the result of the API call.
If you want to have another page, you have to redo another query, with a different page.
So something like that, it's pseudo code, so it probably won't compile as is:
```
Query query = new Query("");
SearchResult<?> result = index.search(query);
// do something with result

query = new Query("").setPage(2);
SearchResult<?> resultPage2 = index.search(query);
// do something with resultPage2
```

**Comment by ElPicador** [comment]
@cecilcosta did you manage to make it work? Can I close this issue?

**Comment by cecilcosta** [comment]
Yes, please close it.
