### ISSUE TITLE
Cannot find addobject from index

### ISSUE THREAD

**Issue by jonathan-bibas** [algolia/algoliasearch-client-java#487]
- Algolia Client Version: 2.17.25
- Language Version: JAVA 8

### Description
Hi i only started to use Algolia but when following the doc, when i want to add record by invoking index.addObject, i can't find the function:
[The method ind the doc](https://www.algolia.com/doc/api-reference/api-methods/add-objects/?language=java#examples)

### Steps To Reproduce
Try to invoke the method as shown in the doc

**Comment by jonathan-bibas** [comment]
Forgot to udate project to Java 8

**Comment by jonathan-bibas** [comment]
Just forgot to update project to Java 8, it seem that on Java 7 it hide some methods

**Comment by julienbourdeau** [comment]
Possibly yes, this project only support Java8+. 👍
