### ISSUE TITLE
com.algolia.search.exceptions.AlgoliaHttpException  body must contain an object

### ISSUE THREAD

**Issue by psjavi** [algolia/algoliasearch-client-java#500]
- Algolia Client Version: 2.18.0
- Language Version: Grails

### Description
Hi, I'm having the following error when I try to send the objects to  the index.

`com.algolia.search.exceptions.AlgoliaHttpException  body must contain an object` 

![x](https://user-images.githubusercontent.com/4563033/43954507-10df4ae2-9c9d-11e8-8b49-8c78eaa64b99.jpg)

### Steps To Reproduce

```
List vehicles = []
vehicles.add((createAlgoliaJsonAd(params) as JSON).toString())
APIClient client = new ApacheAPIClientBuilder(applicationId, apiKey).build()
Index index = client.initIndex(indexName)
index.clear()
index.addObjects(vehicles)

JSONObject createAlgoliaJsonAd(Object params) {
        JSONObject ad = new JSONObject()
        ad.put("maker_s", 'ford')
        ad.put("model_s", 'focus')
        return ad
    }

```
What am I doing wrong?

**Comment by psjavi** [comment]
Also I'm trying this test:

![algolia api rapidapi](https://user-images.githubusercontent.com/4563033/43955764-e18be822-9ca1-11e8-99d6-a2c5476dc8f3.jpg)

**Comment by aseure** [comment]
Hello @psjavi,

Thank you contacting us and for all the details you gave us. Indeed, the way you create and send your objects is not properly done, let me explain.

For ease of use, you only have to create POJO objects for the records you want to send to Algolia. You do not need intermediate JSON objects. The documentation regarding this point can be found [here on our documentation](https://www.algolia.com/doc/api-reference/api-methods/add-objects/).

Your code just needs few changes to be properly working (examples are provided in Java as I'm not proficient enough in Groovy):

**Main.java**
```java
APIClient client = new ApacheAPIClientBuilder(appId, apiKey).build();
Index index = client.initIndex(indexName);

List<Vehicle> vehicles = Arrays.asList(
        new Vehicle().setMaker("ford").setModel("focus")
);

try {
  Task task = index.clear();
  client.waitTask(task);

  TaskSingleIndex taskSingleIndex = index.addObjects(vehicles);
  client.waitTask(taskSingleIndex);

} catch (AlgoliaException e) {
  e.printStackTrace();
}
```

**Vehicle.java**
```java
public class Vehicle {
  private String maker;
  private String model;

  public String getMaker() {
    return maker;
  }

  public Vehicle setMaker(String maker) {
    this.maker = maker;
    return this;
  }

  public String getModel() {
    return model;
  }

  public Vehicle setModel(String model) {
    this.model = model;
    return this;
  }

}
```

**Comment by aseure** [comment]
As for your second message, and the screenshot that comes with it, I'm not sure to understand your question. Could you clarify what is this website and the test and how we may help you?

**Comment by psjavi** [comment]
Hi @aseure thanks a lot for your help, that was the problem, I just only need the POJO object.

It has been my fault, I was translating my Ruby test to Java and I was using JSON instead.

The second picture only was a testing using an external tool in rapidapi.com in order to try if my problem was in my code or not.

Thanks a lot again.
