### ISSUE TITLE
Missing params

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-java#504]
**search**

- [x] [optionalFilters](https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/)
- [x] [sumOrFiltersScores](https://www.algolia.com/doc/api-reference/api-parameters/sumOrFiltersScores/)
- [x] [clickAnalytics](https://www.algolia.com/doc/api-reference/api-parameters/clickAnalytics/)

**Comment by Ant-hem** [comment]
Closed with #540
