### ISSUE TITLE
Change facetFilters type from List<String> to List<Object>

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-java#505]
The current implementation does not support OR operations because the type of `facetFilters` is `List<String>`, which makes it impossible to pass lists of `List<String>`.

To fix this, I'll probably need to change the type for `List<Object>`. @ElPicador Could you confirm that there's no better solution?

**Comment by ElPicador** [comment]
Can't you implement something like this: https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/objects/Distinct.java#L21 ?

With a custom type? Happy to discuss it

**Comment by aseure** [comment]
Oh perfect, this is exactly the kind of example I was looking for actually, I'll try to do it by myself from there. Thanks a lot @ElPicador
