### ISSUE TITLE
Add: JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY as default

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-java#516]
- Algolia Client Version: 2.2.0

### Description
This is an issue, I discovered from a support ticket.
The Java client can't manage to deserialize `List<String>` or `String[]` when it has only one element.

### Steps To Reproduce
You have a Java class with a property which is a list/array of strings. 
You index the Object with a List of only one element to the seach engine.
Try to search the index you'll get this error

`MismatchedInputException: Cannot deserialize instance of java.util.ArrayList out of VALUE_STRING` 

### Solution
Add `mapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)`
to our default mapper's configuration.

cc: @aseure @ElPicador

**Comment by ElPicador** [comment]
Careful when changing the default `mapper` a lot of users are overriding it. So it's better, when possible, to use annotations when we deserialize our own objects.

**Comment by Ant-hem** [comment]
You think it's a bad idea to do the fix?

If it's not a default setting, it means the Java client can't handle the deserialisation  of`String[]` or `List<String>` which has only one element.

 Our customers has to add the following annotation to all theirs`String[]` `List<String>` 
`@JsonFormat(with = JsonFormat.Feature.ACCEPT_SINGLE_VALUE_AS_ARRAY)`

**Comment by julienbourdeau** [comment]
Can a user update the mapper configuration?

**Comment by ElPicador** [comment]
I think the fix is a good idea. Just be careful that the mapper can be and will be overridden. So it's mandatory for us to put the right annotations on our classes. Does it make more sense?

**Comment by Ant-hem** [comment]
Yes! very clear thanks! :)

**Comment by Ant-hem** [comment]
Closed with #540
