### ISSUE TITLE
Async client fails on addObjects()

### ISSUE THREAD

**Issue by ben-manes** [algolia/algoliasearch-client-java#52]
This appears to be a client problem. When hard coding to a list of 1 empty object it fails similarly. The Jackson model doesn't have this `indexName` attribute, so I assume that is part of the client's request.

```
com.algolia.search.exceptions.AlgoliaHttpException: The indexName attribute is only allowed on multiple indexes near line:1 column:339
    at com.algolia.search.http.AlgoliaHttpClient.requestWithRetry(AlgoliaHttpClient.java:68)
    at com.algolia.search.AsyncHttpClient.lambda$requestWithRetry$0(AsyncHttpClient.java:24)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
    ... 7 common frames omitted
```

**Comment by ben-manes** [comment]
When switching to `addObject(batch.get(0))` it is successful, which confirms it is a bug in the client code.

**Comment by ben-manes** [comment]
The `content` in AlgoliaHttpClient for a list containing an empty object is,

``` json
{"requests":[{"body":{"mixins":[]},"indexName":null,"action":"addObject"}]}
```

The request does include the index name, but the nested `BatchAddObjectOperation` does not have it set. If I set the value in the debugger, then the operation completes successfully. It sounds like you forgot to propagate it.

**Comment by ElPicador** [comment]
Could you provide us the failing code?
Are you using a specific ObjectMapper:

**Comment by ben-manes** [comment]
I am using a specific `ObjectMapper`, defined as

```
new ObjectMapper()
  .registerModules(new AfterburnerModule(), new Jdk8Module(),
      new JavaTimeModule(), new GuavaModule(), new JsonOrgModule())
  .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
  .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
```

**Comment by ElPicador** [comment]
The default ObjectMapper specifies `.setSerializationInclusion(JsonInclude.Include.NON_NULL)`, see [here](https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-common/src/main/java/com/algolia/search/Defaults.java#L16). And it's mandatory. 

You are not the first to have this issue. I'll have to look how to improve this. If you have any idea, I'm interested.

**Comment by ben-manes** [comment]
Perhaps you should use `copy()` of the supplied mapper and add this setting?

The reason I used my own was because I wanted to make sure serialization came out properly. Otherwise I'd go back to using `JSONObject` as an intermediate, which seemed wasteful.

**Comment by ElPicador** [comment]
Yes, I still want to provide custom ObjectMapper.

Your idea is interesting. I'll have look.

**Comment by ben-manes** [comment]
After running with this setting, batching works. Thanks!

``` java
return new ApacheAPIClientBuilder(applicationId, apiKey)
    .setObjectMapper(objectMapper.copy()
        .setSerializationInclusion(JsonInclude.Include.NON_NULL))
    .build();
```

**Comment by ElPicador** [comment]
You're welcome. Nonetheless I'll try to find a better solution for this issue.

I've open an issue to tackle this: https://github.com/algolia/algoliasearch-client-java-2/issues/53
