### ISSUE TITLE
FacetFilters not serializing correctly for search

### ISSUE THREAD

**Issue by pjjanak** [algolia/algoliasearch-client-java#522]
- Algolia Client Version: 2.20.0
- Language Version: 1.80_162

### Description
When doing a search using APIClient.multipleQueries() a MultipleQueriesRequests object is created. To get the params for the individual queries, Query.toParams() is called. Query.toParams() then calls, I believe, the incorrect add() method. It uses the method with Object value where FaceFilters should be a CompoundType so getInsideValue() is called which should produce a serializable List<String> or a List<List<String>>.

**Comment by Ant-hem** [comment]
Hello,

Thanks for your contribution 😄 ATM I am working on a release of a new API feature on the client.
Once I am done with this release I will look at your PR.

Thanks,

**Comment by pjjanak** [comment]
Of course! Do you have an eta? We were looking to integrate search fairly soon into our project and the is a blocker for us.

**Comment by Ant-hem** [comment]
I think end of next week or just after christmas. I need to add E2E tests for this PR as well.

**Comment by pjjanak** [comment]
Great :) - let me know if there's anything else I should add in there.

**Comment by Ant-hem** [comment]
hey @pjjanak 

Thanks again for your contribution. I got ahead and added the E2E tests for your PR with #525 so that your fix will be shipped with tomorrow's release.

**Comment by pjjanak** [comment]
Awesome! Thanks ant-hem!

**Comment by Ant-hem** [comment]
You're welcome. Fixed in [2.21.0](https://github.com/algolia/algoliasearch-client-java-2/releases/tag/2.21.0)
