### ISSUE TITLE
Custom ObjectMapper & required properties

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-java#53]
The API clients needs the object mapper to have these properties:
- .setSerializationInclusion(JsonInclude.Include.NON_NULL)
- .enable(JsonGenerator.Feature.AUTO_CLOSE_JSON_CONTENT)
- .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)

But it's also cool to let people choose their object mapping. 
As of today it's a bit broken, because ou can override the default one, but it will loose the required properties

**Comment by ben-manes** [comment]
Thanks!
