### ISSUE TITLE
Change IHttpRequester for HttpRequester (interface) and HttpRequester for ApacheHttpRequester (Apache implementation)

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-java#547]

**Comment by Ant-hem** [comment]
Proposal:  e519ccb and d10b7bc WDYT @aseure @BenoitPerrot 
We could merge this issue with #546 as well.

**Comment by aseure** [comment]
LGTM but are those commits part of a bigger PRs?

**Comment by Ant-hem** [comment]
Part of the main PR. I didn't do a PR for this one.
