### ISSUE TITLE
Remove `browse` in favor of `browseObjects`

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-java#548]
* Also check for `browseRules` / `browseSynonyms`
* Specs incoming :)

**Comment by Ant-hem** [comment]
@aseure all good for `browseRules` and `browseSynonyms`. What about `browseObjects` ? In other clients (.NET) the method is named `browse` and not `browseObjects`

**Comment by Ant-hem** [comment]
Closed with 512a78b
