### ISSUE TITLE
# tests(cts): update send_event/send_events tests adding timestamp

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-java#601]
**Docs**: https://github.com/algolia/algoliasearch-client-specs/pull/31/files.

Here is an example on python: https://github.com/algolia/algoliasearch-client-python/pull/433/files.

**Goal**: make sure developers can set the event timestamp when sending events using send_event/send_events.

**Comment by Ant-hem** [comment]
Users can send timeStamp with the `InsightsEvent` class which is in the signature of every `sendEvents` method

https://github.com/algolia/algoliasearch-client-java-2/blob/d608948f081987ecc6f903e5ede44674db1b4692/algoliasearch-core/src/main/java/com/algolia/search/InsightsClient.java#L140

and 

https://github.com/algolia/algoliasearch-client-java-2/blob/d608948f081987ecc6f903e5ede44674db1b4692/algoliasearch-core/src/main/java/com/algolia/search/models/insights/InsightsEvent.java#L14
