### ISSUE TITLE
set settings.userData field in CTS test for index settings

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-java#606]
Specs: https://github.com/algolia/algoliasearch-client-specs/pull/38

**Comment by Ant-hem** [comment]
Already there: 

https://github.com/algolia/algoliasearch-client-java-2/blob/1a4c815bee336c971bd764dbabac322dcbb236de/algoliasearch-core/src/test/java/com/algolia/search/integration/index/SettingsTest.java#L131-L135
