### ISSUE TITLE
exhaustiveNbHits Missing from SearchResult

### ISSUE THREAD

**Issue by mcgowanb** [algolia/algoliasearch-client-java#717]
- Algolia Client Version: 3.11.0
- Language Version: Java 11

### Description
`exhaustiveNbHits` is not declared as a property in the `SearchResult` object, yet it is getting returned in JSON from the HTTP request. As a result it is not marshalling this property out and we cannot use it on the our front end application

### Steps To Reproduce
Any invocation of `SearchIndex<?>.search(...)`

**Comment by aallam** [comment]
Hello @mcgowanb, thank you for reporting this issue. Please try the new version 3.12.0 it should fix this issue.
