### ISSUE TITLE
Add missing fields in Variant.java

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-java#721]
- Algolia Client Version: 3.X
- Language Version: All

### Description

The [Variant](https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-core/src/main/java/com/algolia/search/models/analytics/Variant.java) POJO seems to be missing lots of fields comparing to the other clients.

Let's update it with all the latest fields.

See C# struct as a reference:
https://github.com/algolia/algoliasearch-client-csharp/blob/master/src/Algolia.Search/Models/Analytics/Variant.cs

**Comment by gaurangagarwal** [comment]
Can i work on this issue ?
