### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by h1alexbel** [algolia/algoliasearch-client-java#782]
Referring to [algolia website](https://www.algolia.com/developers/search-api-java/) java client supports only Java 8 - Java 12. 
So, is it possible that you will support Java 17?

**Comment by aallam** [comment]
Hi @h1alexbel, thanks for your feedback! 
The java client should support Java 17 without issues!

**Comment by h1alexbel** [comment]
@aallam ok, thanks!
