### ISSUE TITLE
Null SearchResult if index does not exist

### ISSUE THREAD

**Issue by ben-manes** [algolia/algoliasearch-client-java#79]
If the index does not exist, e.g. local development's, then `Index#search(query)` returns null. The expected behavior was that it would return back an empty result. Either way, improving the JavaDoc would be beneficial.

**Comment by ElPicador** [comment]
@ben-manes WDYT of the fix?

**Comment by ben-manes** [comment]
It looks good. I think the API might be a little inconsistent. If the index does not exist, on the first addition it is created automatically. So by that logic one would expect only soft errors. A hard failure is reasonable, but the mix makes not obvious without clear JavaDoc. So I could argue either way here, but the JavaDoc update makes it fine.
